### ISSUE TITLE
Reading JP2 causing SIGSEGV

### ISSUE THREAD

**Issue by safris** [dbmdz/imageio-jnr#110]
I have the following code to read JP2 files:

```java
try (final InputStream in = new FileInputStream(path)) {
  final BufferedImage image = ImageIO.read(in);
  ...
}
```

The `ImageIO.read(in)` leads to the following...

```bash
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000000112ee023a, pid=12844, tid=0x000000000000a603
#
# JRE version: Java(TM) SE Runtime Environment (8.0_271-b09) (build 1.8.0_271-b09)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.271-b09 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# J 1231% C2 de.digitalcollections.openjpeg.OpenJpeg.decode(Lde/digitalcollections/openjpeg/InStreamWrapper;Ljava/awt/Rectangle;I)Ljava/awt/image/BufferedImage; (556 bytes) @ 0x0000000112ee023a [0x0000000112edfd80+0x4ba]
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/seva/Work/pano/src/fire-server/receiver/hs_err_pid12844.log[thread 22531 also had an error]

#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
```

I have tried this code on Ubuntu 20.04 (OpenJDK java version "1.8.0_275"), having installed OpenJpeg support with `apt-get install libopenjp2-7`.
I have also tried this code on MacOS (Oracle java version "1.8.0_271"), having installed OpenJpeg support with `brew install openjpeg`.

Running my code in either platform leads to the same SIGSEGV.

**Comment by Horcrux7** [comment]
Occur this with different image files or only with a specific jpeg2000 file? Can you attach this image?

**Comment by safris** [comment]
Sure, here's an example of such an image:

![0](https://user-images.githubusercontent.com/1258414/103504030-d15d3f00-4e88-11eb-9b3d-0a8cbe162744.jpg)

**Comment by Horcrux7** [comment]
I can reproduce this on Windows with OpenJPEG 2.3.1. Because other images are working this must be related to the image file.

**Comment by Horcrux7** [comment]
The image is coded with the YUV (OPJ_CLRSPC_SYCC) color space. This format is not implemented yet.

This color space has 3 components. The first component contains the black/white information. The U and V components for the color information has only the half pixel size. That the components has different size is not expected and produce the crash.

It is simple to prevent the crash. We can throw an exception. A crash is fatal. But an implementation of the color space will be very difficult.

Is an exception ok for you?

**Comment by jbaiter** [comment]
Hey @Horcrux7, an exception would be great, could you make a PR?
