### ISSUE TITLE
New Version

### ISSUE THREAD

**Issue by Horcrux7** [dbmdz/imageio-jnr#119]
The latest version 0.4.4 is one year old. There are many improvements. When will there a new release with this improvments?

Is the lib compatible with OpenJPEG 2.4.0 which should contains security fixes?

**Comment by jbaiter** [comment]
We've just released 0.5.0, sorry it took so damn long, we've been very busy this last year and the library kind of got put on the back burner.
Many thanks to you as well for your contributions, they really are much appreciated!

As for compatibility with 2.4.0, it's definitely compatible. The OpenJPEG project maintains a nice overview of ABI changes across versions, and it seems that 2.4.0 only added a new symbol but didn't remove or change anything.

https://www.openjpeg.org/abi-check/timeline/openjpeg/
