### ISSUE TITLE
Loglevel mismatch

### ISSUE THREAD

**Issue by renevanderark** [dbmdz/imageio-jnr#63]
This turns on the info handler when loglevel is info while info messages are passed on to debug handler
https://github.com/dbmdz/imageio-jnr/blob/c727e8efe1640436c0d8f0b3e47d499b73192dce/imageio-openjpeg/src/main/java/de/digitalcollections/openjpeg/OpenJpeg.java#L57

LOGGER.debug(...)
https://github.com/dbmdz/imageio-jnr/blob/c727e8efe1640436c0d8f0b3e47d499b73192dce/imageio-openjpeg/src/main/java/de/digitalcollections/openjpeg/OpenJpeg.java#L32

should it not be if LOG.isDebugEnabled()?

**Comment by morpheus-87** [comment]
Fixed with #79.

**Comment by morpheus-87** [comment]
You can find the release [here](https://github.com/dbmdz/imageio-jnr/releases/tag/0.4.4).
